<?php

declare(strict_types=1);

namespace Tests\Support;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

/**
 * The one implementation behind every module-boundary guard — ADR-002.
 *
 * WHY THIS CLASS EXISTS. The guards it replaces used
 * `glob('Modules/X/**\/*.php')`, and PHP's glob has no recursive `**`: the
 * pattern degrades to a single `*`, so it matched only files sitting exactly
 * one directory below the module root. Measured before the rewrite:
 * **5 files out of ~40** in Contestants. The controller guard was worse —
 * `Controllers/**\/*.php` matched **nothing at all**, because controllers sit
 * directly in `Controllers/`, so no controller in the repository had ever been
 * checked.
 *
 * Those guards were green. A green test that inspects nothing is worse than a
 * missing one: it answers a question nobody re-asks.
 *
 * The module list is also discovered here rather than written down. The old
 * global guard carried a hardcoded array of fifteen names, and `Organization`
 * — added in Epic 2 — was never added to it, so an entire module sat outside
 * the check in both directions.
 */
final class ModuleBoundary
{
    /**
     * Cross-module imports that exist today and are NOT being fixed here.
     *
     * A baseline, not an exemption: every entry is one real violation, named
     * by file and by the exact class it reaches for. New violations fail the
     * guard immediately; these are visible debt with a paper trail.
     *
     * Generated by measurement, not written by hand. Deliberately without
     * wildcards — a pattern would hide the next one that matched it.
     *
     * The 21 fall into three groups, worst first:
     *
     *   ELOQUENT MODELS ACROSS MODULES (7) — Reports, Search, Sponsors and
     *   Videos reading another module's tables directly. The real coupling,
     *   and the reason the controller guard existing but being blind mattered.
     *
     *   REPOSITORY CONTRACTS AND DOMAIN TYPES (13) — Applications and
     *   Evaluations depending on other modules' abstractions. Wrong by
     *   ADR-002, but abstractions rather than tables.
     *
     *   PermissionCatalog (1) — a genuine conflict between two guards, see
     *   the note on that entry below.
     *
     * @var array<string, array<int, string>>
     */
    public const BASELINE = [
        'Applications/Application/UseCases/SubmitApplicationUseCase.php' => [
            'Modules\Contestants\Domain\Repositories\ContestantRepositoryContract',
            'Modules\Organization\Domain\Repositories\CenterRepositoryContract',
            'Modules\Organization\Domain\Repositories\CircleRepositoryContract',
            'Modules\Organization\Domain\Repositories\ContestantMembershipRepositoryContract',
            'Modules\Organization\Domain\ValueObjects\CenterId',
            'Modules\Organization\Domain\ValueObjects\CircleId',
        ],
        'Applications/Presentation/HTTP/Controllers/ApplicationController.php' => [
            'Modules\Contestants\Domain\Repositories\ContestantRepositoryContract',
        ],

        // A CONFLICT BETWEEN TWO GUARDS, not ordinary debt.
        // PermissionSourceOfTruthTest forbids writing a permission name as a
        // string literal, so a runtime `can()` check must ask the catalogue
        // for it — and the catalogue lives in Core's Infrastructure, which
        // this guard forbids importing. There is no way to satisfy both today.
        // Resolving it means either exposing permission naming through
        // CoreServiceContract or exempting the catalogue explicitly, and that
        // is a design decision this epic deliberately does not take.
        'Contestants/Presentation/HTTP/Controllers/AdminContestantController.php' => [
            'Modules\Core\Infrastructure\Permissions\PermissionCatalog',
        ],

        'Evaluations/Domain/Services/RankingService.php' => [
            'Modules\Competition\Domain\Strategies\QualificationStrategy',
            'Modules\Competition\Domain\Strategies\TieBreakerStrategy',
        ],
        'Evaluations/Presentation/HTTP/Controllers/AdminEvaluationController.php' => [
            'Modules\Applications\Infrastructure\Database\Models\ApplicationModel',
        ],
        'Evaluations/Presentation/HTTP/Controllers/AppealController.php' => [
            'Modules\Applications\Domain\Repositories\ApplicationRepositoryContract',
            'Modules\Contestants\Domain\Repositories\ContestantRepositoryContract',
        ],
        'Evaluations/Presentation/HTTP/Controllers/JudgeEvaluationController.php' => [
            'Modules\Judges\Domain\Repositories\JudgeRepositoryContract',
        ],
        'Reports/Presentation/HTTP/Controllers/AdminReportController.php' => [
            'Modules\Applications\Infrastructure\Database\Models\ApplicationModel',
            'Modules\Contestants\Infrastructure\Database\Models\ContestantModel',
            'Modules\Evaluations\Infrastructure\Database\Models\EvaluationModel',
        ],
        'Search/Presentation/HTTP/Controllers/PublicSearchController.php' => [
            'Modules\Contestants\Infrastructure\Database\Models\ContestantModel',
            'Modules\Streaming\Infrastructure\Database\Models\StreamModel',
        ],
        'Sponsors/Presentation/HTTP/Resources/SponsorResource.php' => [
            'Modules\Media\Infrastructure\Database\Models\MediaAssetModel',
        ],
        'Videos/Presentation/HTTP/Controllers/ContestantVideoController.php' => [
            'Modules\Media\Infrastructure\Database\Models\MediaAssetModel',
        ],
    ];

    /**
     * Controllers that import an Eloquent model, as they stood when the guard
     * that should have caught them was repaired.
     *
     * A SEPARATE RULE FROM THE ONE ABOVE, and worth keeping separate. The
     * BASELINE constant is about ADR-002 — one module reaching into another.
     * This is about ADR-009/ADR-012 layering: a controller reaching past its
     * own application layer into its own module's tables. Most of these are a
     * controller and a model inside the same module, which the boundary rule
     * has no opinion about at all.
     *
     * 33 imports across 26 controllers. None of them was ever reported,
     * because `Controllers/**\/*.php` matched no file: the guard ran, asserted
     * nothing, and was marked risky for its entire life. Repairing the glob is
     * what produced this list.
     *
     * Not fixed here. Routing 26 controllers through repositories or use cases
     * is a refactor across nearly every module in the platform, and this epic
     * is about making the tests tell the truth — not about rewriting the code
     * they test. The debt is now visible and cannot grow.
     *
     * @var array<string, array<int, string>>
     */
    public const CONTROLLER_MODEL_BASELINE = [
        'Applications/Presentation/HTTP/Controllers/ApplicationController.php' => [
            'Modules\\Applications\\Infrastructure\\Database\\Models\\ApplicationModel',
        ],
        'Content/Presentation/HTTP/Controllers/AdminContentController.php' => [
            'Modules\\Content\\Infrastructure\\Database\\Models\\AnnouncementModel',
        ],
        'Content/Presentation/HTTP/Controllers/PublicContentController.php' => [
            'Modules\\Content\\Infrastructure\\Database\\Models\\AnnouncementModel',
        ],
        'Core/Presentation/HTTP/Controllers/AuthController.php' => [
            'Modules\\Core\\Infrastructure\\Database\\Models\\UserModel',
        ],
        'Core/Presentation/HTTP/Controllers/UserController.php' => [
            'Modules\\Core\\Infrastructure\\Database\\Models\\UserModel',
        ],
        'Countries/Presentation/HTTP/Controllers/CountryController.php' => [
            'Modules\\Countries\\Infrastructure\\Database\\Models\\CountryModel',
        ],
        'Evaluations/Presentation/HTTP/Controllers/AdminEvaluationController.php' => [
            'Modules\\Applications\\Infrastructure\\Database\\Models\\ApplicationModel',
            'Modules\\Evaluations\\Infrastructure\\Database\\Models\\EvaluationModel',
            'Modules\\Evaluations\\Infrastructure\\Database\\Models\\StageResultModel',
        ],
        'Evaluations/Presentation/HTTP/Controllers/AppealController.php' => [
            'Modules\\Evaluations\\Infrastructure\\Database\\Models\\AppealModel',
        ],
        'Evaluations/Presentation/HTTP/Controllers/JudgeEvaluationController.php' => [
            'Modules\\Evaluations\\Infrastructure\\Database\\Models\\EvaluationModel',
        ],
        'Judges/Presentation/HTTP/Controllers/JudgeController.php' => [
            'Modules\\Judges\\Infrastructure\\Database\\Models\\JudgeModel',
        ],
        'Media/Presentation/HTTP/Controllers/AdminMediaController.php' => [
            'Modules\\Media\\Infrastructure\\Database\\Models\\MediaAssetModel',
        ],
        'Media/Presentation/HTTP/Controllers/ContestantMediaController.php' => [
            'Modules\\Media\\Infrastructure\\Database\\Models\\MediaAssetModel',
        ],
        'Notifications/Presentation/HTTP/Controllers/AdminNotificationController.php' => [
            'Modules\\Notifications\\Infrastructure\\Database\\Models\\NotificationLogModel',
        ],
        'Notifications/Presentation/HTTP/Controllers/ContestantNotificationController.php' => [
            'Modules\\Notifications\\Infrastructure\\Database\\Models\\NotificationLogModel',
        ],
        'Organization/Presentation/HTTP/Controllers/CenterController.php' => [
            'Modules\\Organization\\Infrastructure\\Database\\Models\\CenterModel',
        ],
        'Organization/Presentation/HTTP/Controllers/CircleController.php' => [
            'Modules\\Organization\\Infrastructure\\Database\\Models\\CircleModel',
        ],
        'Organization/Presentation/HTTP/Controllers/MembershipController.php' => [
            'Modules\\Organization\\Infrastructure\\Database\\Models\\ContestantMembershipModel',
        ],
        'Reports/Presentation/HTTP/Controllers/AdminReportController.php' => [
            'Modules\\Applications\\Infrastructure\\Database\\Models\\ApplicationModel',
            'Modules\\Contestants\\Infrastructure\\Database\\Models\\ContestantModel',
            'Modules\\Evaluations\\Infrastructure\\Database\\Models\\EvaluationModel',
            'Modules\\Reports\\Infrastructure\\Database\\Models\\ExportModel',
        ],
        'Search/Presentation/HTTP/Controllers/AdminSearchController.php' => [
            'Modules\\Search\\Infrastructure\\Database\\Models\\IndexingLogModel',
        ],
        'Search/Presentation/HTTP/Controllers/PublicSearchController.php' => [
            'Modules\\Contestants\\Infrastructure\\Database\\Models\\ContestantModel',
            'Modules\\Streaming\\Infrastructure\\Database\\Models\\StreamModel',
        ],
        'Sponsors/Presentation/HTTP/Controllers/AdminSponsorController.php' => [
            'Modules\\Sponsors\\Infrastructure\\Database\\Models\\SponsorModel',
        ],
        'Sponsors/Presentation/HTTP/Controllers/PublicSponsorController.php' => [
            'Modules\\Sponsors\\Infrastructure\\Database\\Models\\SponsorModel',
        ],
        'Streaming/Presentation/HTTP/Controllers/AdminStreamController.php' => [
            'Modules\\Streaming\\Infrastructure\\Database\\Models\\StreamModel',
        ],
        'Streaming/Presentation/HTTP/Controllers/PublicStreamController.php' => [
            'Modules\\Streaming\\Infrastructure\\Database\\Models\\StreamModel',
        ],
        'Videos/Presentation/HTTP/Controllers/AdminVideoController.php' => [
            'Modules\\Videos\\Infrastructure\\Database\\Models\\VideoModel',
        ],
        'Videos/Presentation/HTTP/Controllers/ContestantVideoController.php' => [
            'Modules\\Media\\Infrastructure\\Database\\Models\\MediaAssetModel',
            'Modules\\Videos\\Infrastructure\\Database\\Models\\VideoModel',
        ],
    ];

    /** Every module, read from disk so a new one cannot be forgotten. */
    public static function modules(): array
    {
        $root = base_path('Modules');
        $modules = [];

        foreach (scandir($root) ?: [] as $entry) {
            if ($entry !== '.' && $entry !== '..' && is_dir("$root/$entry")) {
                $modules[] = $entry;
            }
        }

        sort($modules);

        return $modules;
    }

    /**
     * Every PHP file under a directory. Recursive, unlike the glob this
     * replaces.
     *
     * @return array<int, string>
     */
    public static function phpFilesUnder(string $directory): array
    {
        if (! is_dir($directory)) {
            return [];
        }

        $files = [];

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($directory, RecursiveDirectoryIterator::SKIP_DOTS)
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->isFile() && $file->getExtension() === 'php') {
                $files[] = str_replace('\\', '/', $file->getPathname());
            }
        }

        sort($files);

        return $files;
    }

    /** A module's own files, excluding its tests and its published contracts. */
    public static function sourceFilesOf(string $module): array
    {
        return array_values(array_filter(
            self::phpFilesUnder(base_path("Modules/$module")),
            fn (string $path): bool => ! str_contains($path, '/Tests/') && ! str_contains($path, '/Contracts/')
        ));
    }

    /** The path as the baseline names it: "Module/Relative/Path.php". */
    public static function relativePath(string $absolute): string
    {
        return str_replace(str_replace('\\', '/', base_path('Modules')).'/', '', str_replace('\\', '/', $absolute));
    }

    /**
     * Every cross-module import in one module that does not go through
     * Contracts/, after the platform exemptions below.
     *
     * @return array<string, array<int, string>> relative path => imported FQCNs
     */
    public static function violationsIn(string $module): array
    {
        $found = [];

        foreach (self::sourceFilesOf($module) as $path) {
            $relative = self::relativePath($path);

            preg_match_all(
                '/use (Modules\\\\(\w+)\\\\((?!Contracts\\\\)[\w\\\\]+));/',
                (string) file_get_contents($path),
                $matches,
                PREG_SET_ORDER
            );

            foreach ($matches as [, $fqcn, $target]) {
                if ($target === $module || self::isPlatformExempt($relative, $fqcn)) {
                    continue;
                }

                $found[$relative][] = $fqcn;
            }
        }

        foreach ($found as $relative => $imports) {
            $found[$relative] = array_values(array_unique($imports));
            sort($found[$relative]);
        }

        ksort($found);

        return $found;
    }

    /**
     * Two shared pieces of platform machinery that every module legitimately
     * uses, exempted by rule rather than listed file by file.
     *
     * They are not coupling between modules — they are the platform's own
     * scaffolding, and there is nowhere else for them to live. 49 of the 70
     * imports the corrected scan found are these two, which is why the raw
     * number is not the interesting one.
     */
    private static function isPlatformExempt(string $relative, string $fqcn): bool
    {
        // The shared schema helper. Every migration in the repository uses it
        // to declare UUID primary keys and soft deletes consistently; a
        // migration that hand-rolled them would be the actual defect.
        if (str_contains($relative, '/Database/Migrations/') && $fqcn === 'Modules\Core\Database\PlatformBlueprint') {
            return true;
        }

        // The shared aggregate concerns — HasDomainEvents and friends. A trait
        // every aggregate root in every module applies.
        return str_starts_with($fqcn, 'Modules\Core\Domain\Concerns\\');
    }

    /**
     * Violations that are NOT in the baseline — the ones a guard must fail on.
     *
     * @return array<int, string> human-readable "file -> class" lines
     */
    public static function unbaselinedViolationsIn(string $module): array
    {
        $new = [];

        foreach (self::violationsIn($module) as $relative => $imports) {
            $allowed = self::BASELINE[$relative] ?? [];

            foreach (array_diff($imports, $allowed) as $import) {
                $new[] = "$relative -> $import";
            }
        }

        return $new;
    }

    /**
     * Every model a controller imports, keyed by controller.
     *
     * @return array<string, array<int, string>>
     */
    public static function controllerModelImports(): array
    {
        $found = [];

        foreach (self::modules() as $module) {
            foreach (self::phpFilesUnder(base_path("Modules/$module/Presentation/HTTP/Controllers")) as $path) {
                preg_match_all(
                    '/use (Modules\\\\\w+\\\\[\w\\\\]*Models\\\\\w+);/',
                    (string) file_get_contents($path),
                    $matches
                );

                if ($matches[1] !== []) {
                    $imports = array_values(array_unique($matches[1]));
                    sort($imports);
                    $found[self::relativePath($path)] = $imports;
                }
            }
        }

        ksort($found);

        return $found;
    }

    /** @return array<int, string> */
    public static function unbaselinedControllerModelImports(): array
    {
        $new = [];

        foreach (self::controllerModelImports() as $relative => $imports) {
            foreach (array_diff($imports, self::CONTROLLER_MODEL_BASELINE[$relative] ?? []) as $import) {
                $new[] = "$relative -> $import";
            }
        }

        return $new;
    }

    /** @return array<int, string> */
    public static function staleControllerBaselineEntries(): array
    {
        $live = self::controllerModelImports();
        $stale = [];

        foreach (self::CONTROLLER_MODEL_BASELINE as $relative => $imports) {
            foreach ($imports as $import) {
                if (! in_array($import, $live[$relative] ?? [], true)) {
                    $stale[] = "$relative -> $import";
                }
            }
        }

        return $stale;
    }

    /**
     * Baseline entries that no longer describe a real violation.
     *
     * Without this the list rots: an import removed by later work would leave
     * a permanent entry, and the baseline would slowly stop meaning "this is
     * what we still owe". Paying debt down has to shrink the list, and this
     * is what makes that mandatory rather than polite.
     *
     * @return array<int, string>
     */
    public static function staleBaselineEntries(): array
    {
        $live = [];

        foreach (self::modules() as $module) {
            foreach (self::violationsIn($module) as $relative => $imports) {
                $live[$relative] = $imports;
            }
        }

        $stale = [];

        foreach (self::BASELINE as $relative => $imports) {
            foreach ($imports as $import) {
                if (! in_array($import, $live[$relative] ?? [], true)) {
                    $stale[] = "$relative -> $import";
                }
            }
        }

        return $stale;
    }
}
